# NOTE: It is necessary to explicitly set the distribution to "trusty" due to
# the complex 'matrix: include:' logic below
# More information: https://github.com/travis-ci/travis-ci/issues/5448
dist: trusty

language: python

# NOTE: Explicit Python versions make Travis job description more informative
matrix:
  include:
    - env: TOX_ENV=py36
      python: "3.6"
    - env: TOX_ENV=docs
      python: "3.6"
    - env: TOX_ENV=linters
      python: "3.6"
    - env: TOX_ENV=packaging
      python: "3.6"

install: pip install tox

script: tox -e $TOX_ENV

after_success:
 - pip install codecov
 - codecov -e TOX_ENV
